# action.yml
name: 'Slack notification action'
description: 'A simple Slack notification action which runs using a bot token.'
inputs:
  token:  # id of input
    description: 'The slack bot token.'
    required: true
    default: ''
  message:  # id of input
    description: 'The message to send'
    required: true
    default: ''
  channel:
    description: 'The channel ID to send the message to'
    required: true
    default: ''
outputs:
  timestamp:
    description: 'The timestamp at which the message was posted. This is used to update or to reply to a message in thread'
  channel:
    description: 'The ID of the channel this message was posted to.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --token=${{ inputs.token }}
    - --message=${{ inputs.message }}
    - --channel=${{ inputs.channel }}
branding:
  icon: "arrow-right-circle"
  color: purple
author: "Gergely Brautigam"
